title: Modernist Homestead
description: Biological Logistics & Land Systems
url: "https://petersalvato.github.io/modernisthomestead-constellation"
baseurl: "/modernisthomestead-constellation"

markdown: kramdown
permalink: /:year/:month/:day/:title/
sass:
  style: compressed

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
